### ISSUE TITLE
应用内无法连接到redis，emmm

### ISSUE THREAD

**Issue by astimes** [yanlongma/docker-lnmp#3]
应用内无法连接到redis，emmm

**Comment by yanlongma** [comment]
看样子是好了 ^_^

**Comment by astimes** [comment]
> 看样子是好了 ^_^

是的，因为以前的环境都是在同一个环境里面的 redis配置127.0.0.1 没问题
现在需要在代码里配置redis容器的ip，不然127.0.0.1这种访问的不是redis容器的ip
