### ISSUE TITLE
Cannot start service php-fpm

### ISSUE THREAD

**Issue by ganyu** [yanlongma/docker-lnmp#4]
![图片](https://user-images.githubusercontent.com/4115112/77129035-7b501400-6a8d-11ea-8077-6d995c75930b.png)
$  docker-compose up -d nginx
Starting lnmp-php-pfm ...
Starting lnmp-php-pfm ... error

ERROR: for lnmp-php-pfm  Cannot start service php-fpm: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/c/Program Files/Docker Toolbox/docker-lnmp/php-fpm/conf-7.2/php-fpm.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged/usr/local/etc/php-fpm.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for php-fpm  Cannot start service php-fpm: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/c/Program Files/Docker Toolbox/docker-lnmp/php-fpm/conf-7.2/php-fpm.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged/usr/local/etc/php-fpm.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
您好，在执行docker-compose up -d nginx报上面的错，能帮忙看下吗

**Comment by yanlongma** [comment]
用 docker 命令单独启动一个 php 镜像试试有没有报错，能否启动。

**Comment by ganyu** [comment]
> 用 docker 命令单独启动一个 php 镜像试试有没有报错，能否启动。

试过了，还是报一样的错
$  docker-compose up -d php-fpm
Starting lnmp-php-pfm ... error

ERROR: for lnmp-php-pfm  Cannot start service php-fpm: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/c/Program Files/Docker Toolbox/docker-lnmp/php-fpm/conf-7.2/php-fpm.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged/usr/local/etc/php-fpm.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for php-fpm  Cannot start service php-fpm: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/c/Program Files/Docker Toolbox/docker-lnmp/php-fpm/conf-7.2/php-fpm.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/0a38987c01b8cff9db5583d6593da0f8d8f4b74da6838eb8fd8fe8ebe6c4610c/merged/usr/local/etc/php-fpm.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by yanlongma** [comment]
加 vx：json_vip
